// <auto-generated />
using System;
using BPMeasurementApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPMeasurementApp.Migrations
{
    [DbContext(typeof(MeasurementDbContext))]
    [Migration("20250609004618_positionId")]
    partial class positionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPMeasurementApp.Entities.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementId"));

                    b.Property<DateOnly>("DateTaken")
                        .HasColumnType("date");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("MeasurementId");

                    b.HasIndex("PositionId");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            MeasurementId = 1,
                            DateTaken = new DateOnly(2008, 2, 7),
                            Diastolic = 121,
                            PositionId = "st",
                            Systolic = 181
                        },
                        new
                        {
                            MeasurementId = 2,
                            DateTaken = new DateOnly(2005, 12, 29),
                            Diastolic = 91,
                            PositionId = "ld",
                            Systolic = 142
                        },
                        new
                        {
                            MeasurementId = 3,
                            DateTaken = new DateOnly(2002, 11, 24),
                            Diastolic = 85,
                            PositionId = "st",
                            Systolic = 131
                        },
                        new
                        {
                            MeasurementId = 4,
                            DateTaken = new DateOnly(1998, 5, 8),
                            Diastolic = 79,
                            PositionId = "si",
                            Systolic = 122
                        },
                        new
                        {
                            MeasurementId = 5,
                            DateTaken = new DateOnly(1996, 2, 9),
                            Diastolic = 78,
                            PositionId = "si",
                            Systolic = 118
                        });
                });

            modelBuilder.Entity("BPMeasurementApp.Entities.Position", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            PositionId = "st",
                            Name = "Standing"
                        },
                        new
                        {
                            PositionId = "si",
                            Name = "Sitting"
                        },
                        new
                        {
                            PositionId = "ld",
                            Name = "Lying down"
                        });
                });

            modelBuilder.Entity("BPMeasurementApp.Entities.Measurement", b =>
                {
                    b.HasOne("BPMeasurementApp.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
